name: Debug Workflow

on: push

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Test Debug Output
        run: echo "This is a debug test step"