name: Manual Trigger Workflow with Environment Variable
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        if: ${{ inputs.environment == 'production' }}
        run: |
          echo "Deploying to production environment..."
      - name: Deploy to staging
        if: ${{ inputs.environment == 'staging' }}
        run: |
          echo "Deploying to staging environment..."
      - name: Deploy to development
        if: ${{ inputs.environment == 'development' }}
        run: |
          echo "Deploying to development environment..."