name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment for deployment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      deploy_version:
        description: 'Version to deploy'
        required: true
        default: 'v1.0.0'
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying to ${{ inputs.environment }} environment, version: ${{ inputs.deploy_version }}"